import DanceLesson from './DanceLesson';
/* eslint-disable */

const renegadeLesson = {
  _id: '4c813a0a-0e39-4697-9ae2-a913d2944fd3',
  header: { clipName: 'renegade.mp4', lessonTitle: 'AutoGenerated Lesson 2021/02/26 15:03' },
  segmentBreaks: [0.7666666666666667, 2.2, 3.1666666666666665, 4.633333333333334, 5.4, 8.033333333333333, 9.333333333333334, 10.733333333333333],
  activities: [{
    title: 'Dance Preview (Initial)', type: 'learn', startTime: 0, endTime: 12.233333333333333, focusedSegments: [0, 1, 2, 3, 4, 5, 6, 7, 8], keyFrames: [], practiceSpeeds: [1], instructions: "This is the dance you're going to learn (don't worry, we'll break this down for you)", timedInstructions: [],
  }, {
    title: 'Dance Preview (Segment Overview)', type: 'learn', startTime: -0.01, endTime: 12.233333333333333, focusedSegments: [0, 1, 2, 3, 4, 5, 6, 7, 8], keyFrames: [0.7666666666666667, 2.2, 3.1666666666666665, 4.633333333333334, 5.4, 8.033333333333333, 9.333333333333334, 10.733333333333333], practiceSpeeds: [0.5], instructions: "You'll learn this dance in 9 parts", timedInstructions: [{ startTime: 0.0, endTime: 0.7666666666666667, text: 'Part 1' }, { startTime: 0.7666666666666667, endTime: 2.2, text: 'Part 2' }, { startTime: 2.2, endTime: 3.1666666666666665, text: 'Part 3' }, { startTime: 3.1666666666666665, endTime: 4.633333333333334, text: 'Part 4' }, { startTime: 4.633333333333334, endTime: 5.4, text: 'Part 5' }, { startTime: 5.4, endTime: 8.033333333333333, text: 'Part 6' }, { startTime: 8.033333333333333, endTime: 9.333333333333334, text: 'Part 7' }, { startTime: 9.333333333333334, endTime: 10.733333333333333, text: 'Part 8' }, { startTime: 10.733333333333333, endTime: 12.233333333333333, text: 'Part 9' }],
  }, {
    title: 'Segment 1, (Complete, single move)', type: 'learn', startTime: 0.0, endTime: 0.7666666666666667, focusedSegments: [0], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Segment #1 is short. Try it!', timedInstructions: [],
  }, {
    title: 'Segment 2 Preview', type: 'learn', startTime: 0.7666666666666667, endTime: 2.2, focusedSegments: [1], keyFrames: [0.7666666666666667, 1.5], practiceSpeeds: [0.5], timedInstructions: [{ startTime: 0.7666666666666667, endTime: 0.8666666666666667, text: "Now we're going to learn segment 2. (2 moves)" }, { startTime: 0.7666666666666667, endTime: 1.5, text: 'Dance Move #1' }, { startTime: 1.5, endTime: 2.2, text: 'Dance Move #2' }],
  }, {
    title: 'Segment 2, Move 1', type: 'learn', startTime: 0.7666666666666667, endTime: 1.5, focusedSegments: [1], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #1 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 2, Move 2', type: 'learn', startTime: 1.5, endTime: 2.2, focusedSegments: [1], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #2 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 2, Integration', type: 'learn', startTime: 0.7666666666666667, endTime: 2.2, focusedSegments: [1], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Now practice these moves together', timedInstructions: [],
  }, {
    title: 'Segment 1-2 integration', type: 'learn', startTime: 0.0, endTime: 2.2, focusedSegments: [0, 1], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 1 - 2 together', timedInstructions: [],
  }, {
    title: 'Segment 3 Preview', type: 'learn', startTime: 2.2, endTime: 3.1666666666666665, focusedSegments: [2], keyFrames: [2.2, 2.3], practiceSpeeds: [0.5], timedInstructions: [{ startTime: 2.2, endTime: 2.3000000000000003, text: "Now we're going to learn segment 3. (2 moves)" }, { startTime: 2.2, endTime: 2.3, text: 'Dance Move #1' }, { startTime: 2.3, endTime: 3.1666666666666665, text: 'Dance Move #2' }],
  }, {
    title: 'Segment 3, Move 1', type: 'learn', startTime: 2.2, endTime: 2.3, focusedSegments: [2], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #1 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 3, Move 2', type: 'learn', startTime: 2.3, endTime: 3.1666666666666665, focusedSegments: [2], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #2 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 3, Integration', type: 'learn', startTime: 2.2, endTime: 3.1666666666666665, focusedSegments: [2], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Now practice these moves together', timedInstructions: [],
  }, {
    title: 'Segment 1-3 integration', type: 'learn', startTime: 0.0, endTime: 3.1666666666666665, focusedSegments: [0, 1, 2], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 1 - 3 together', timedInstructions: [],
  }, {
    title: 'Segment 4 Preview', type: 'learn', startTime: 3.1666666666666665, endTime: 4.633333333333334, focusedSegments: [3], keyFrames: [3.1666666666666665, 3.9, 4.466666666666667], practiceSpeeds: [0.5], timedInstructions: [{ startTime: 3.1666666666666665, endTime: 3.2666666666666666, text: "Now we're going to learn segment 4. (3 moves)" }, { startTime: 3.1666666666666665, endTime: 3.9, text: 'Dance Move #1' }, { startTime: 3.9, endTime: 4.466666666666667, text: 'Dance Move #2' }, { startTime: 4.466666666666667, endTime: 4.633333333333334, text: 'Dance Move #3' }],
  }, {
    title: 'Segment 4, Move 1', type: 'learn', startTime: 3.1666666666666665, endTime: 3.9, focusedSegments: [3], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #1 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 4, Move 2', type: 'learn', startTime: 3.9, endTime: 4.466666666666667, focusedSegments: [3], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #2 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 4, Move 3', type: 'learn', startTime: 4.466666666666667, endTime: 4.633333333333334, focusedSegments: [3], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #3 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 4, Integration', type: 'learn', startTime: 3.1666666666666665, endTime: 4.633333333333334, focusedSegments: [3], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Now practice these moves together', timedInstructions: [],
  }, {
    title: 'Segment 2-4 integration', type: 'learn', startTime: 0.7666666666666667, endTime: 4.633333333333334, focusedSegments: [1, 2, 3], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 2 - 4 together', timedInstructions: [],
  }, {
    title: 'Segment 5 Preview', type: 'learn', startTime: 4.633333333333334, endTime: 5.4, focusedSegments: [4], keyFrames: [4.633333333333334, 4.733333333333333], practiceSpeeds: [0.5], timedInstructions: [{ startTime: 4.633333333333334, endTime: 4.733333333333333, text: "Now we're going to learn segment 5. (2 moves)" }, { startTime: 4.633333333333334, endTime: 4.733333333333333, text: 'Dance Move #1' }, { startTime: 4.733333333333333, endTime: 5.4, text: 'Dance Move #2' }],
  }, {
    title: 'Segment 5, Move 1', type: 'learn', startTime: 4.633333333333334, endTime: 4.733333333333333, focusedSegments: [4], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #1 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 5, Move 2', type: 'learn', startTime: 4.733333333333333, endTime: 5.4, focusedSegments: [4], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #2 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 5, Integration', type: 'learn', startTime: 4.633333333333334, endTime: 5.4, focusedSegments: [4], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Now practice these moves together', timedInstructions: [],
  }, {
    title: 'Segment 3-5 integration', type: 'learn', startTime: 2.2, endTime: 5.4, focusedSegments: [2, 3, 4], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 3 - 5 together', timedInstructions: [],
  }, {
    title: 'Segment 6 Preview', type: 'learn', startTime: 5.4, endTime: 8.033333333333333, focusedSegments: [5], keyFrames: [5.4, 5.633333333333334, 6.533333333333333, 7.833333333333333], practiceSpeeds: [0.5], timedInstructions: [{ startTime: 5.4, endTime: 5.5, text: "Now we're going to learn segment 6. (4 moves)" }, { startTime: 5.4, endTime: 5.633333333333334, text: 'Dance Move #1' }, { startTime: 5.633333333333334, endTime: 6.533333333333333, text: 'Dance Move #2' }, { startTime: 6.533333333333333, endTime: 7.833333333333333, text: 'Dance Move #3' }, { startTime: 7.833333333333333, endTime: 8.033333333333333, text: 'Dance Move #4' }],
  }, {
    title: 'Segment 6, Move 1', type: 'learn', startTime: 5.4, endTime: 5.633333333333334, focusedSegments: [5], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #1 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 6, Move 2', type: 'learn', startTime: 5.633333333333334, endTime: 6.533333333333333, focusedSegments: [5], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #2 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 6, Move 3', type: 'learn', startTime: 6.533333333333333, endTime: 7.833333333333333, focusedSegments: [5], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #3 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 6, Move 4', type: 'learn', startTime: 7.833333333333333, endTime: 8.033333333333333, focusedSegments: [5], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #4 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 6, Integration', type: 'learn', startTime: 5.4, endTime: 8.033333333333333, focusedSegments: [5], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Now practice these moves together', timedInstructions: [],
  }, {
    title: 'Segment 4-6 integration', type: 'learn', startTime: 3.1666666666666665, endTime: 8.033333333333333, focusedSegments: [3, 4, 5], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 4 - 6 together', timedInstructions: [],
  }, {
    title: 'Segment 7 Preview', type: 'learn', startTime: 8.033333333333333, endTime: 9.333333333333334, focusedSegments: [6], keyFrames: [8.033333333333333, 8.2, 8.466666666666667], practiceSpeeds: [0.5], timedInstructions: [{ startTime: 8.033333333333333, endTime: 8.133333333333333, text: "Now we're going to learn segment 7. (3 moves)" }, { startTime: 8.033333333333333, endTime: 8.2, text: 'Dance Move #1' }, { startTime: 8.2, endTime: 8.466666666666667, text: 'Dance Move #2' }, { startTime: 8.466666666666667, endTime: 9.333333333333334, text: 'Dance Move #3' }],
  }, {
    title: 'Segment 7, Move 1', type: 'learn', startTime: 8.033333333333333, endTime: 8.2, focusedSegments: [6], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #1 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 7, Move 2', type: 'learn', startTime: 8.2, endTime: 8.466666666666667, focusedSegments: [6], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #2 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 7, Move 3', type: 'learn', startTime: 8.466666666666667, endTime: 9.333333333333334, focusedSegments: [6], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #3 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 7, Integration', type: 'learn', startTime: 8.033333333333333, endTime: 9.333333333333334, focusedSegments: [6], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Now practice these moves together', timedInstructions: [],
  }, {
    title: 'Segment 5-7 integration', type: 'learn', startTime: 4.633333333333334, endTime: 9.333333333333334, focusedSegments: [4, 5, 6], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 5 - 7 together', timedInstructions: [],
  }, {
    title: 'Segment 8 Preview', type: 'learn', startTime: 9.333333333333334, endTime: 10.733333333333333, focusedSegments: [7], keyFrames: [9.333333333333334, 10.266666666666667], practiceSpeeds: [0.5], timedInstructions: [{ startTime: 9.333333333333334, endTime: 9.433333333333334, text: "Now we're going to learn segment 8. (2 moves)" }, { startTime: 9.333333333333334, endTime: 10.266666666666667, text: 'Dance Move #1' }, { startTime: 10.266666666666667, endTime: 10.733333333333333, text: 'Dance Move #2' }],
  }, {
    title: 'Segment 8, Move 1', type: 'learn', startTime: 9.333333333333334, endTime: 10.266666666666667, focusedSegments: [7], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #1 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 8, Move 2', type: 'learn', startTime: 10.266666666666667, endTime: 10.733333333333333, focusedSegments: [7], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #2 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 8, Integration', type: 'learn', startTime: 9.333333333333334, endTime: 10.733333333333333, focusedSegments: [7], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Now practice these moves together', timedInstructions: [],
  }, {
    title: 'Segment 6-8 integration', type: 'learn', startTime: 5.4, endTime: 10.733333333333333, focusedSegments: [5, 6, 7], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 6 - 8 together', timedInstructions: [],
  }, {
    title: 'Segment 9 Preview', type: 'learn', startTime: 10.733333333333333, endTime: 12.233333333333333, focusedSegments: [8], keyFrames: [10.733333333333333, 11.566666666666666], practiceSpeeds: [0.5], timedInstructions: [{ startTime: 10.733333333333333, endTime: 10.833333333333332, text: "Now we're going to learn segment 9. (2 moves)" }, { startTime: 10.733333333333333, endTime: 11.566666666666666, text: 'Dance Move #1' }, { startTime: 11.566666666666666, endTime: 12.233333333333333, text: 'Dance Move #2' }],
  }, {
    title: 'Segment 9, Move 1', type: 'learn', startTime: 10.733333333333333, endTime: 11.566666666666666, focusedSegments: [8], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #1 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 9, Move 2', type: 'learn', startTime: 11.566666666666666, endTime: 12.233333333333333, focusedSegments: [8], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #2 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 9, Integration', type: 'learn', startTime: 10.733333333333333, endTime: 12.233333333333333, focusedSegments: [8], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Now practice these moves together', timedInstructions: [],
  }, {
    title: 'Segment 7-9 integration', type: 'learn', startTime: 8.033333333333333, endTime: 12.233333333333333, focusedSegments: [6, 7, 8], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 7 - 9 together', timedInstructions: [],
  }, {
    title: 'Dance Review @ 50', type: 'learn', startTime: 0, endTime: 12.233333333333333, focusedSegments: [0, 1, 2, 3, 4, 5, 6, 7, 8], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's try the whole dance at 50% speed", timedInstructions: [],
  }, {
    title: 'Dance Review @ 60', type: 'learn', startTime: 0, endTime: 12.233333333333333, focusedSegments: [0, 1, 2, 3, 4, 5, 6, 7, 8], keyFrames: [], practiceSpeeds: [0.6], instructions: 'Now try it at 60%', timedInstructions: [],
  }, {
    title: 'Dance Review @ 75', type: 'learn', startTime: 0, endTime: 12.233333333333333, focusedSegments: [0, 1, 2, 3, 4, 5, 6, 7, 8], keyFrames: [], practiceSpeeds: [0.75], instructions: 'Now try it at 75%', timedInstructions: [],
  }, {
    title: 'Dance Review @ 85', type: 'learn', startTime: 0, endTime: 12.233333333333333, focusedSegments: [0, 1, 2, 3, 4, 5, 6, 7, 8], keyFrames: [], practiceSpeeds: [0.85], instructions: 'Now try it at 85%', timedInstructions: [],
  }, {
    title: 'Dance Review @ 100', type: 'learn', startTime: 0, endTime: 12.233333333333333, focusedSegments: [0, 1, 2, 3, 4, 5, 6, 7, 8], keyFrames: [], practiceSpeeds: [1.0], instructions: 'Now try it at 100%', timedInstructions: [],
  }],
} as DanceLesson;

const unhunhLesson = {
  _id: 'bb49478f-0055-4653-a06b-16f8d3417ffe',
  header: { clipName: 'unhhunh.mp4', lessonTitle: 'AutoGenerated Lesson 2021/02/26 15:03' },
  segmentBreaks: [0.7666666666666667, 1.9, 3.5, 5.166666666666667, 6.9, 8.7, 10.3, 11.466666666666667, 12.966666666666667, 15.966666666666667, 16.833333333333332],
  activities: [{
    title: 'Dance Preview (Initial)', type: 'learn', startTime: 0, endTime: 19.266666666666666, focusedSegments: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], keyFrames: [], practiceSpeeds: [1], instructions: "This is the dance you're going to learn (don't worry, we'll break this down for you)", timedInstructions: [],
  }, {
    title: 'Dance Preview (Segment Overview)', type: 'learn', startTime: -0.01, endTime: 19.266666666666666, focusedSegments: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], keyFrames: [0.7666666666666667, 1.9, 3.5, 5.166666666666667, 6.9, 8.7, 10.3, 11.466666666666667, 12.966666666666667, 15.966666666666667, 16.833333333333332], practiceSpeeds: [0.5], instructions: "You'll learn this dance in 12 parts", timedInstructions: [{ startTime: 0.0, endTime: 0.7666666666666667, text: 'Part 1' }, { startTime: 0.7666666666666667, endTime: 1.9, text: 'Part 2' }, { startTime: 1.9, endTime: 3.5, text: 'Part 3' }, { startTime: 3.5, endTime: 5.166666666666667, text: 'Part 4' }, { startTime: 5.166666666666667, endTime: 6.9, text: 'Part 5' }, { startTime: 6.9, endTime: 8.7, text: 'Part 6' }, { startTime: 8.7, endTime: 10.3, text: 'Part 7' }, { startTime: 10.3, endTime: 11.466666666666667, text: 'Part 8' }, { startTime: 11.466666666666667, endTime: 12.966666666666667, text: 'Part 9' }, { startTime: 12.966666666666667, endTime: 15.966666666666667, text: 'Part 10' }, { startTime: 15.966666666666667, endTime: 16.833333333333332, text: 'Part 11' }, { startTime: 16.833333333333332, endTime: 19.266666666666666, text: 'Part 12' }],
  }, {
    title: 'Segment 1, (Complete, single move)', type: 'learn', startTime: 0.0, endTime: 0.7666666666666667, focusedSegments: [0], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Segment #1 is short. Try it!', timedInstructions: [],
  }, {
    title: 'Segment 2, (Complete, single move)', type: 'learn', startTime: 0.7666666666666667, endTime: 1.9, focusedSegments: [1], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Segment #2 is short. Try it!', timedInstructions: [],
  }, {
    title: 'Segment 1-2 integration', type: 'learn', startTime: 0.0, endTime: 1.9, focusedSegments: [0, 1], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 1 - 2 together', timedInstructions: [],
  }, {
    title: 'Segment 3, (Complete, single move)', type: 'learn', startTime: 1.9, endTime: 3.5, focusedSegments: [2], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Segment #3 is short. Try it!', timedInstructions: [],
  }, {
    title: 'Segment 1-3 integration', type: 'learn', startTime: 0.0, endTime: 3.5, focusedSegments: [0, 1, 2], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 1 - 3 together', timedInstructions: [],
  }, {
    title: 'Segment 4 Preview', type: 'learn', startTime: 3.5, endTime: 5.166666666666667, focusedSegments: [3], keyFrames: [3.5, 4.533333333333333, 4.833333333333333], practiceSpeeds: [0.5], timedInstructions: [{ startTime: 3.5, endTime: 3.6, text: "Now we're going to learn segment 4. (3 moves)" }, { startTime: 3.5, endTime: 4.533333333333333, text: 'Dance Move #1' }, { startTime: 4.533333333333333, endTime: 4.833333333333333, text: 'Dance Move #2' }, { startTime: 4.833333333333333, endTime: 5.166666666666667, text: 'Dance Move #3' }],
  }, {
    title: 'Segment 4, Move 1', type: 'learn', startTime: 3.5, endTime: 4.533333333333333, focusedSegments: [3], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #1 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 4, Move 2', type: 'learn', startTime: 4.533333333333333, endTime: 4.833333333333333, focusedSegments: [3], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #2 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 4, Move 3', type: 'learn', startTime: 4.833333333333333, endTime: 5.166666666666667, focusedSegments: [3], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #3 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 4, Integration', type: 'learn', startTime: 3.5, endTime: 5.166666666666667, focusedSegments: [3], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Now practice these moves together', timedInstructions: [],
  }, {
    title: 'Segment 2-4 integration', type: 'learn', startTime: 0.7666666666666667, endTime: 5.166666666666667, focusedSegments: [1, 2, 3], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 2 - 4 together', timedInstructions: [],
  }, {
    title: 'Segment 5 Preview', type: 'learn', startTime: 5.166666666666667, endTime: 6.9, focusedSegments: [4], keyFrames: [5.166666666666667, 5.4, 5.666666666666667, 5.833333333333333, 6.033333333333333], practiceSpeeds: [0.5], timedInstructions: [{ startTime: 5.166666666666667, endTime: 5.266666666666667, text: "Now we're going to learn segment 5. (5 moves)" }, { startTime: 5.166666666666667, endTime: 5.4, text: 'Dance Move #1' }, { startTime: 5.4, endTime: 5.666666666666667, text: 'Dance Move #2' }, { startTime: 5.666666666666667, endTime: 5.833333333333333, text: 'Dance Move #3' }, { startTime: 5.833333333333333, endTime: 6.033333333333333, text: 'Dance Move #4' }, { startTime: 6.033333333333333, endTime: 6.9, text: 'Dance Move #5' }],
  }, {
    title: 'Segment 5, Move 1', type: 'learn', startTime: 5.166666666666667, endTime: 5.4, focusedSegments: [4], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #1 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 5, Move 2', type: 'learn', startTime: 5.4, endTime: 5.666666666666667, focusedSegments: [4], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #2 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 5, Move 3', type: 'learn', startTime: 5.666666666666667, endTime: 5.833333333333333, focusedSegments: [4], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #3 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 5, Move 4', type: 'learn', startTime: 5.833333333333333, endTime: 6.033333333333333, focusedSegments: [4], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #4 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 5, Move 5', type: 'learn', startTime: 6.033333333333333, endTime: 6.9, focusedSegments: [4], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #5 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 5, Integration', type: 'learn', startTime: 5.166666666666667, endTime: 6.9, focusedSegments: [4], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Now practice these moves together', timedInstructions: [],
  }, {
    title: 'Segment 3-5 integration', type: 'learn', startTime: 1.9, endTime: 6.9, focusedSegments: [2, 3, 4], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 3 - 5 together', timedInstructions: [],
  }, {
    title: 'Segment 6 Preview', type: 'learn', startTime: 6.9, endTime: 8.7, focusedSegments: [5], keyFrames: [6.9, 7.966666666666667, 8.5], practiceSpeeds: [0.5], timedInstructions: [{ startTime: 6.9, endTime: 7.0, text: "Now we're going to learn segment 6. (3 moves)" }, { startTime: 6.9, endTime: 7.966666666666667, text: 'Dance Move #1' }, { startTime: 7.966666666666667, endTime: 8.5, text: 'Dance Move #2' }, { startTime: 8.5, endTime: 8.7, text: 'Dance Move #3' }],
  }, {
    title: 'Segment 6, Move 1', type: 'learn', startTime: 6.9, endTime: 7.966666666666667, focusedSegments: [5], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #1 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 6, Move 2', type: 'learn', startTime: 7.966666666666667, endTime: 8.5, focusedSegments: [5], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #2 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 6, Move 3', type: 'learn', startTime: 8.5, endTime: 8.7, focusedSegments: [5], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #3 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 6, Integration', type: 'learn', startTime: 6.9, endTime: 8.7, focusedSegments: [5], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Now practice these moves together', timedInstructions: [],
  }, {
    title: 'Segment 4-6 integration', type: 'learn', startTime: 3.5, endTime: 8.7, focusedSegments: [3, 4, 5], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 4 - 6 together', timedInstructions: [],
  }, {
    title: 'Segment 7, (Complete, single move)', type: 'learn', startTime: 8.7, endTime: 10.3, focusedSegments: [6], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Segment #7 is short. Try it!', timedInstructions: [],
  }, {
    title: 'Segment 5-7 integration', type: 'learn', startTime: 5.166666666666667, endTime: 10.3, focusedSegments: [4, 5, 6], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 5 - 7 together', timedInstructions: [],
  }, {
    title: 'Segment 8 Preview', type: 'learn', startTime: 10.3, endTime: 11.466666666666667, focusedSegments: [7], keyFrames: [10.3, 10.666666666666666], practiceSpeeds: [0.5], timedInstructions: [{ startTime: 10.3, endTime: 10.4, text: "Now we're going to learn segment 8. (2 moves)" }, { startTime: 10.3, endTime: 10.666666666666666, text: 'Dance Move #1' }, { startTime: 10.666666666666666, endTime: 11.466666666666667, text: 'Dance Move #2' }],
  }, {
    title: 'Segment 8, Move 1', type: 'learn', startTime: 10.3, endTime: 10.666666666666666, focusedSegments: [7], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #1 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 8, Move 2', type: 'learn', startTime: 10.666666666666666, endTime: 11.466666666666667, focusedSegments: [7], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #2 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 8, Integration', type: 'learn', startTime: 10.3, endTime: 11.466666666666667, focusedSegments: [7], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Now practice these moves together', timedInstructions: [],
  }, {
    title: 'Segment 6-8 integration', type: 'learn', startTime: 6.9, endTime: 11.466666666666667, focusedSegments: [5, 6, 7], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 6 - 8 together', timedInstructions: [],
  }, {
    title: 'Segment 9 Preview', type: 'learn', startTime: 11.466666666666667, endTime: 12.966666666666667, focusedSegments: [8], keyFrames: [11.466666666666667, 11.666666666666666, 12.066666666666666], practiceSpeeds: [0.5], timedInstructions: [{ startTime: 11.466666666666667, endTime: 11.566666666666666, text: "Now we're going to learn segment 9. (3 moves)" }, { startTime: 11.466666666666667, endTime: 11.666666666666666, text: 'Dance Move #1' }, { startTime: 11.666666666666666, endTime: 12.066666666666666, text: 'Dance Move #2' }, { startTime: 12.066666666666666, endTime: 12.966666666666667, text: 'Dance Move #3' }],
  }, {
    title: 'Segment 9, Move 1', type: 'learn', startTime: 11.466666666666667, endTime: 11.666666666666666, focusedSegments: [8], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #1 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 9, Move 2', type: 'learn', startTime: 11.666666666666666, endTime: 12.066666666666666, focusedSegments: [8], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #2 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 9, Move 3', type: 'learn', startTime: 12.066666666666666, endTime: 12.966666666666667, focusedSegments: [8], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #3 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 9, Integration', type: 'learn', startTime: 11.466666666666667, endTime: 12.966666666666667, focusedSegments: [8], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Now practice these moves together', timedInstructions: [],
  }, {
    title: 'Segment 7-9 integration', type: 'learn', startTime: 8.7, endTime: 12.966666666666667, focusedSegments: [6, 7, 8], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 7 - 9 together', timedInstructions: [],
  }, {
    title: 'Segment 10 Preview', type: 'learn', startTime: 12.966666666666667, endTime: 15.966666666666667, focusedSegments: [9], keyFrames: [12.966666666666667, 15.833333333333334], practiceSpeeds: [0.5], timedInstructions: [{ startTime: 12.966666666666667, endTime: 13.066666666666666, text: "Now we're going to learn segment 10. (2 moves)" }, { startTime: 12.966666666666667, endTime: 15.833333333333334, text: 'Dance Move #1' }, { startTime: 15.833333333333334, endTime: 15.966666666666667, text: 'Dance Move #2' }],
  }, {
    title: 'Segment 10, Move 1', type: 'learn', startTime: 12.966666666666667, endTime: 15.833333333333334, focusedSegments: [9], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #1 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 10, Move 2', type: 'learn', startTime: 15.833333333333334, endTime: 15.966666666666667, focusedSegments: [9], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #2 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 10, Integration', type: 'learn', startTime: 12.966666666666667, endTime: 15.966666666666667, focusedSegments: [9], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Now practice these moves together', timedInstructions: [],
  }, {
    title: 'Segment 8-10 integration', type: 'learn', startTime: 10.3, endTime: 15.966666666666667, focusedSegments: [7, 8, 9], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 8 - 10 together', timedInstructions: [],
  }, {
    title: 'Segment 11 Preview', type: 'learn', startTime: 15.966666666666667, endTime: 16.833333333333332, focusedSegments: [10], keyFrames: [15.966666666666667, 16.5], practiceSpeeds: [0.5], timedInstructions: [{ startTime: 15.966666666666667, endTime: 16.066666666666666, text: "Now we're going to learn segment 11. (2 moves)" }, { startTime: 15.966666666666667, endTime: 16.5, text: 'Dance Move #1' }, { startTime: 16.5, endTime: 16.833333333333332, text: 'Dance Move #2' }],
  }, {
    title: 'Segment 11, Move 1', type: 'learn', startTime: 15.966666666666667, endTime: 16.5, focusedSegments: [10], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #1 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 11, Move 2', type: 'learn', startTime: 16.5, endTime: 16.833333333333332, focusedSegments: [10], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #2 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 11, Integration', type: 'learn', startTime: 15.966666666666667, endTime: 16.833333333333332, focusedSegments: [10], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Now practice these moves together', timedInstructions: [],
  }, {
    title: 'Segment 9-11 integration', type: 'learn', startTime: 11.466666666666667, endTime: 16.833333333333332, focusedSegments: [8, 9, 10], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 9 - 11 together', timedInstructions: [],
  }, {
    title: 'Segment 12 Preview', type: 'learn', startTime: 16.833333333333332, endTime: 19.266666666666666, focusedSegments: [11], keyFrames: [16.833333333333332, 16.866666666666667, 17.266666666666666, 17.466666666666665, 18.7], practiceSpeeds: [0.5], timedInstructions: [{ startTime: 16.833333333333332, endTime: 16.933333333333334, text: "Now we're going to learn segment 12. (5 moves)" }, { startTime: 16.833333333333332, endTime: 16.866666666666667, text: 'Dance Move #1' }, { startTime: 16.866666666666667, endTime: 17.266666666666666, text: 'Dance Move #2' }, { startTime: 17.266666666666666, endTime: 17.466666666666665, text: 'Dance Move #3' }, { startTime: 17.466666666666665, endTime: 18.7, text: 'Dance Move #4' }, { startTime: 18.7, endTime: 19.266666666666666, text: 'Dance Move #5' }],
  }, {
    title: 'Segment 12, Move 1', type: 'learn', startTime: 16.833333333333332, endTime: 16.866666666666667, focusedSegments: [11], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #1 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 12, Move 2', type: 'learn', startTime: 16.866666666666667, endTime: 17.266666666666666, focusedSegments: [11], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #2 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 12, Move 3', type: 'learn', startTime: 17.266666666666666, endTime: 17.466666666666665, focusedSegments: [11], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #3 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 12, Move 4', type: 'learn', startTime: 17.466666666666665, endTime: 18.7, focusedSegments: [11], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #4 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 12, Move 5', type: 'learn', startTime: 18.7, endTime: 19.266666666666666, focusedSegments: [11], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's practice move #5 in this segment", timedInstructions: [],
  }, {
    title: 'Segment 12, Integration', type: 'learn', startTime: 16.833333333333332, endTime: 19.266666666666666, focusedSegments: [11], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Now practice these moves together', timedInstructions: [],
  }, {
    title: 'Segment 10-12 integration', type: 'learn', startTime: 12.966666666666667, endTime: 19.266666666666666, focusedSegments: [9, 10, 11], keyFrames: [], practiceSpeeds: [0.5], instructions: 'Practice doing segments 10 - 12 together', timedInstructions: [],
  }, {
    title: 'Dance Review @ 50', type: 'learn', startTime: 0, endTime: 19.266666666666666, focusedSegments: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], keyFrames: [], practiceSpeeds: [0.5], instructions: "Let's try the whole dance at 50% speed", timedInstructions: [],
  }, {
    title: 'Dance Review @ 60', type: 'learn', startTime: 0, endTime: 19.266666666666666, focusedSegments: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], keyFrames: [], practiceSpeeds: [0.6], instructions: 'Now try it at 60%', timedInstructions: [],
  }, {
    title: 'Dance Review @ 75', type: 'learn', startTime: 0, endTime: 19.266666666666666, focusedSegments: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], keyFrames: [], practiceSpeeds: [0.75], instructions: 'Now try it at 75%', timedInstructions: [],
  }, {
    title: 'Dance Review @ 85', type: 'learn', startTime: 0, endTime: 19.266666666666666, focusedSegments: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], keyFrames: [], practiceSpeeds: [0.85], instructions: 'Now try it at 85%', timedInstructions: [],
  }, {
    title: 'Dance Review @ 100', type: 'learn', startTime: 0, endTime: 19.266666666666666, focusedSegments: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], keyFrames: [], practiceSpeeds: [1.0], instructions: 'Now try it at 100%', timedInstructions: [],
  }],
} as DanceLesson;

export default interface DanceEntry {
  title: string;
  videoSrc: string;
  thumbnail: string;
  animatedThumb: string;
  hovering: boolean;
  lessons: Array<DanceLesson>;
}

export interface LessonSelection {
  dance: DanceEntry;
  lesson: DanceLesson;
}

export const dances: Array<DanceEntry> = [
  {
    title: 'Renegade',
    videoSrc: 'dances/renegade.mp4',
    thumbnail: 'dances/renegade.jpg',
    animatedThumb: 'dances/renegade.gif',
    hovering: false,
    lessons: [
      {
        _id: '1',
        header: {
          clipName: 'renegade.mp4',
          lessonTitle: 'Lesson 1',
        },
        segmentBreaks: [3.45, 7.02, 9.9],
        activities: [
          {
            title: 'Overview',
            type: 'learn',
            startTime: 0,
            endTime: -1,

            timedInstructions: [
              {
                startTime: 0.0,
                endTime: 0.01,
                text: "We'll learn this dance in 4 parts.",
              },
              {
                startTime: 0.1,
                endTime: 3.45,
                text: "Here's the first part",
              },
              {
                startTime: 3.45,
                endTime: 7.02,
                text: "Here's the second part",
              },
              {
                startTime: 7.02,
                endTime: 9.9,
                text: "Here's the third part",
              },
              {
                startTime: 9.9,
                endTime: Infinity,
                text: "Here's the last part",
              },
            ],
            keyFrames: [
              // {
              //   time: 0.1,
              //   instruction: "We'll learn this dance in 4 parts.",
              //   pauseDuration: 2
              // },
              {
                time: 3.45,
              // instruction: "End of the first part"
              }, {
                time: 7.02,
              // instruction: "End of the second part"
              }, {
                time: 9.9,
              // instruction: "End of the third part"
              }],
            practiceSpeeds: [0.50],
          },
          {
            title: 'Learn Part 1',
            type: 'learn',
            startTime: 0,
            endTime: 3.45,
            focusedSegments: [0],
            practiceSpeeds: [0.5, 0.75, 1],
            startInstruction: "Let's learn part 1",
            timedInstructions: [
              // {
              //   startTime: 0.01,
              //   endTime: 0.48,
              //   text: "Double High-five"
              // }, {
              //   startTime: 0.48,
              //   endTime: 1.3,
              //   text: "Arm Swing"
              // },{
              //   startTime: 1.3,
              //   endTime: 1.75,
              //   text: "Cheer"
              // }, {
              //   startTime: 1.75,
              //   endTime: 3.3,
              //   text: "Left-Right Bop"
              // }
            ],
            keyFrames: [{
              time: 0.01,
              instruction: 'Move 1: Double High-five',
              pauseDuration: 2,
              // manualResume: true
            },
            {
              time: 0.48,
              instruction: 'Move 2: Arm Swing',
              pauseDuration: 2,
            },
            // {
            //   time: 0.6,
            //   pauseDuration: 0.75
            // }, {
            //   time: 0.8,
            //   pauseDuration: 0.75
            // }, {
            //   time: 1,
            //   pauseDuration: 0.75
            // },
            {
              time: 1.3,
              pauseDuration: 2,
              instruction: 'Move 3: Cheer',
            },
            // {
            //   time: 1.53,
            //   pauseDuration: 0.75
            // },
            {
              time: 1.75,
              pauseDuration: 2,
              instruction: 'Move 4: Left-Right Bop',
            },
            {
              time: 2.38,
              pauseDuration: 2,
              instruction: 'Move 5: Look Back',
            },
            {
              time: 2.88,
              pauseDuration: 2,
              instruction: 'Move 6: Arms Over & Cross',
            },
            ],
          },
          {
            title: 'Practice Part 1',
            type: 'game',
            startTime: 0,
            endTime: 3.3,
            keyFrames: [0, 0.1, 0.2, 0.3, 0.65, 0.9, 0.95, 1, 2, 3],
          },
        ],
      },
      renegadeLesson,
    ],
  },
  {
    title: 'Unh Hunhh',
    videoSrc: 'dances/unhhunh.mp4',
    thumbnail: 'dances/unhhunh.jpg',
    animatedThumb: 'dances/unhhunh.gif',
    hovering: false,
    lessons: [unhunhLesson],
  },
];
